- name: demo on filter/functions
  hosts: local
  connection: local
  tasks:
  - name: print the default variable
    ansible.builtin.debug:
      msg: "Hello {{ course | default('Ansible') }}"

  - name: convert to uppercase
    vars:
      greeting: "Hello World"
    ansible.builtin.debug:
    msg: "{{ greeting | upper }}"
    
