- name: configure mysql server
  hosts: mysql
  become: yes
  vars:
    mysql_root_password: ExpenseApp@1
  tasks:
  - name: Install MySQL libraries
    ansible.builtin.pip:
      name : "{{ item }}"
      executable: pip3.9
    loops:
    - cryptography
    - PyMySQL

    - name: Install MYSQL server
      ansible.builtin.debug:
        name: mysql-server
        state: installed
    - name: start and enable mysql server
      ansible.builtin.service:
        name: mysql
        state: started
        enabled: yes
    - name: connect the mysql server
      community.mysql.mysql_info:
        login_usr: root
        login_password: "{{ MySql_root_password }}"
        login_host: mysql.daws.online
      register: mysql_info
      ignore_errors: true

    - name: print the output
      ansible.builtin.debug:
        msg: "MySQL info: {{ mysql_info }}"

    - name: setup root login_password
      ansible.builtin.command: " mysql_secure_installation --set-root-pass ExpanseApp@1 "
    when: mysql_info.failed is true